-- DLP Risk Analyzer - Complete Database Setup Script
-- Compatible with Entity Framework Core mappings
-- PostgreSQL 16+ with TimescaleDB extension required

-- Enable TimescaleDB extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================================
-- 1. System Settings Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS system_settings (
    key character varying(100) NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_system_settings" PRIMARY KEY (key)
);

-- ============================================================================
-- 2. Daily Summaries Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS daily_summaries (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    total_incidents integer NOT NULL,
    high_risk_count integer NOT NULL,
    avg_risk_score double precision NOT NULL,
    unique_users integer NOT NULL,
    departments_affected integer NOT NULL,
    CONSTRAINT "PK_daily_summaries" PRIMARY KEY ("Id")
);

-- ============================================================================
-- 3. Department Summaries Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS department_summaries (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    department text NOT NULL,
    total_incidents integer NOT NULL,
    high_risk_count integer NOT NULL,
    avg_risk_score double precision NOT NULL,
    unique_users integer NOT NULL,
    date date,
    CONSTRAINT "PK_department_summaries" PRIMARY KEY ("Id")
);

-- ============================================================================
-- 4. User Risk Trends Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_risk_trends (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    user_email text NOT NULL,
    date date NOT NULL,
    total_incidents integer NOT NULL,
    risk_score integer NOT NULL,
    trend_direction text NOT NULL,
    CONSTRAINT "PK_user_risk_trends" PRIMARY KEY ("Id")
);

-- ============================================================================
-- 5. Incidents Table (TimescaleDB Hypertable)
-- ============================================================================
CREATE TABLE IF NOT EXISTS incidents (
    id integer NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    user_email text NOT NULL,
    department text,
    severity integer NOT NULL,
    data_type text,
    policy text,
    channel text,
    risk_score integer,
    repeat_count integer NOT NULL DEFAULT 0,
    data_sensitivity integer NOT NULL DEFAULT 0,
    "RiskLevel" text,
    "RecommendedAction" text,
    "IOBs" text[],
    CONSTRAINT "PK_incidents" PRIMARY KEY (id, timestamp)
);

-- Create indexes for incidents table
CREATE INDEX IF NOT EXISTS "IX_incidents_department" ON incidents (department);
CREATE INDEX IF NOT EXISTS "IX_incidents_risk_score" ON incidents (risk_score);
CREATE INDEX IF NOT EXISTS "IX_incidents_timestamp" ON incidents (timestamp);
CREATE INDEX IF NOT EXISTS "IX_incidents_user_email" ON incidents (user_email);

-- Convert incidents table to TimescaleDB hypertable
-- Note: This will fail if hypertable already exists, use IF NOT EXISTS
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM timescaledb_information.hypertables 
        WHERE hypertable_name = 'incidents'
    ) THEN
        PERFORM create_hypertable('incidents', 'timestamp', if_not_exists => TRUE);
        RAISE NOTICE 'Hypertable "incidents" created successfully';
    ELSE
        RAISE NOTICE 'Hypertable "incidents" already exists';
    END IF;
END $$;

-- ============================================================================
-- 6. AI Behavioral Analyses Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_behavioral_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(50) NOT NULL,
    entity_id character varying(255) NOT NULL,
    analysis_date timestamp with time zone NOT NULL,
    risk_score integer NOT NULL,
    anomaly_level character varying(20) NOT NULL,
    ai_explanation text NOT NULL,
    ai_recommendation text NOT NULL,
    reference_incident_ids text NOT NULL,
    analysis_metadata text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_ai_behavioral_analyses" PRIMARY KEY (id)
);

-- Create indexes for ai_behavioral_analyses table
CREATE INDEX IF NOT EXISTS "IX_ai_behavioral_analyses_analysis_date" ON ai_behavioral_analyses (analysis_date);
CREATE INDEX IF NOT EXISTS "IX_ai_behavioral_analyses_anomaly_level" ON ai_behavioral_analyses (anomaly_level);
CREATE INDEX IF NOT EXISTS "IX_ai_behavioral_analyses_entity_type_entity_id" ON ai_behavioral_analyses (entity_type, entity_id);

-- ============================================================================
-- 7. Audit Logs Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    timestamp timestamp with time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    user_name character varying(100) NOT NULL,
    user_role character varying(50),
    action character varying(200) NOT NULL,
    resource character varying(255),
    details text,
    ip_address character varying(45),
    user_agent character varying(500),
    success boolean NOT NULL,
    error_message text,
    status_code integer,
    duration_ms bigint,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY (id)
);

-- Create indexes for audit_logs table
CREATE INDEX IF NOT EXISTS "IX_audit_logs_event_type" ON audit_logs (event_type);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_timestamp" ON audit_logs (timestamp);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_timestamp_event_type" ON audit_logs (timestamp, event_type);
CREATE INDEX IF NOT EXISTS "IX_audit_logs_user_name" ON audit_logs (user_name);

-- ============================================================================
-- 8. Anomaly Detections Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS anomaly_detections (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_email character varying(255) NOT NULL,
    metric_type character varying(50) NOT NULL,
    current_value double precision NOT NULL,
    baseline_mean double precision NOT NULL,
    baseline_std_dev double precision NOT NULL,
    anomaly_score double precision NOT NULL,
    severity character varying(20) NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    CONSTRAINT "PK_anomaly_detections" PRIMARY KEY (id)
);

-- Create indexes for anomaly_detections table
CREATE INDEX IF NOT EXISTS "IX_anomaly_detections_user_email" ON anomaly_detections (user_email);
CREATE INDEX IF NOT EXISTS "IX_anomaly_detections_timestamp" ON anomaly_detections (timestamp);
CREATE INDEX IF NOT EXISTS "IX_anomaly_detections_severity" ON anomaly_detections (severity);
CREATE INDEX IF NOT EXISTS "IX_anomaly_detections_user_email_timestamp" ON anomaly_detections (user_email, timestamp);

-- ============================================================================
-- 9. EF Core Migration History Table (Optional but recommended)
-- ============================================================================
-- This table tracks which migrations have been applied
-- If you're using manual SQL instead of migrations, you can skip this
-- But it's recommended to create it to prevent EF Core from trying to apply migrations
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Insert migration records to mark them as applied (optional)
-- Only do this if you want EF Core to think migrations are already applied
-- Uncomment and adjust migration IDs based on your actual migration files:
/*
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES 
    ('20251109184015_AddSystemSettingsTable', '8.0.0'),
    ('20251117155157_AddAIBehavioralAnalysis', '8.0.0'),
    ('20251117182303_AddAuditLogs', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
*/

-- ============================================================================
-- Verification Queries
-- ============================================================================
-- Run these queries to verify all tables were created successfully:

-- SELECT table_name FROM information_schema.tables 
-- WHERE table_schema = 'public' 
-- AND table_name IN ('system_settings', 'daily_summaries', 'department_summaries', 
--                    'user_risk_trends', 'incidents', 'ai_behavioral_analyses', 
--                    'audit_logs', 'anomaly_detections')
-- ORDER BY table_name;

-- SELECT hypertable_name FROM timescaledb_information.hypertables 
-- WHERE hypertable_name = 'incidents';

-- ============================================================================
-- Notes
-- ============================================================================
-- 1. This script uses IF NOT EXISTS to prevent errors if tables already exist
-- 2. TimescaleDB extension must be enabled before running this script
-- 3. The incidents table is converted to a hypertable for time-series optimization
-- 4. All column names match Entity Framework Core mappings exactly
-- 5. Indexes are created to optimize query performance
-- 6. Primary keys and constraints match EF Core configuration
-- 7. After running this script, set "Database:AutoMigrate": false in appsettings.json

