// <auto-generated />
using System;
using System.Collections.Generic;
using DLP.RiskAnalyzer.Analyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DLP.RiskAnalyzer.Analyzer.Migrations
{
    [DbContext(typeof(AnalyzerDbContext))]
    [Migration("20260225095442_AddMissingTables")]
    partial class AddMissingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Data.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("standard")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Models.AIBehavioralAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AIExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_explanation");

                    b.Property<string>("AIRecommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_recommendation");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("analysis_date");

                    b.Property<string>("AnalysisMetadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("analysis_metadata");

                    b.Property<string>("AnomalyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("anomaly_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ReferenceIncidentIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_incident_ids");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("AnomalyLevel");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ai_behavioral_analyses", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Resource")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserName");

                    b.HasIndex("Timestamp", "EventType");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Models.AzureAIExplanation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnomalyDetectedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("anomaly_detected");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<DateTime[]>("TimestampArray")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("UserEmail");

                    b.ToTable("ai_explanations", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.AnomalyDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnomalyScore")
                        .HasColumnType("integer")
                        .HasColumnName("anomaly_score");

                    b.Property<double>("BaselineMean")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_mean");

                    b.Property<double>("BaselineStdDev")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_std_dev");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("current_value");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metric_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail", "Timestamp");

                    b.ToTable("anomaly_detections", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgRiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_risk_score");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DepartmentsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("departments_affected");

                    b.Property<int>("HighRiskCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_risk_count");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<int>("UniqueUsers")
                        .HasColumnType("integer")
                        .HasColumnName("unique_users");

                    b.HasKey("Id");

                    b.ToTable("daily_summaries", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DepartmentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgRiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_risk_score");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<int>("HighRiskCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_risk_count");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<int>("UniqueUsers")
                        .HasColumnType("integer")
                        .HasColumnName("unique_users");

                    b.HasKey("Id");

                    b.ToTable("department_summaries", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DomainFeatureDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key_name");

                    b.HasKey("Id");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.ToTable("domain_feature_definitions", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DomainFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("integer")
                        .HasColumnName("domain_id");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("DomainId", "FeatureId")
                        .IsUnique();

                    b.ToTable("domain_feature_values", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<int>("DataSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("data_sensitivity");

                    b.Property<string>("DataType")
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Destination")
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("HostName")
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<List<string>>("IOBs")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsRemediated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_remediated");

                    b.Property<string>("LoginName")
                        .HasColumnType("text")
                        .HasColumnName("login_name");

                    b.Property<int>("MaxMatches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_matches");

                    b.Property<string>("Policy")
                        .HasColumnType("text")
                        .HasColumnName("policy");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemediatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("remediated_at");

                    b.Property<string>("RemediatedBy")
                        .HasColumnType("text")
                        .HasColumnName("remediated_by");

                    b.Property<string>("RemediationAction")
                        .HasColumnType("text")
                        .HasColumnName("remediation_action");

                    b.Property<string>("RemediationNotes")
                        .HasColumnType("text")
                        .HasColumnName("remediation_notes");

                    b.Property<int>("RepeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("repeat_count");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Team")
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("ViolationTriggers")
                        .HasColumnType("text")
                        .HasColumnName("violation_triggers");

                    b.HasKey("Id", "Timestamp");

                    b.HasIndex("Action");

                    b.HasIndex("Department");

                    b.HasIndex("IsRemediated");

                    b.HasIndex("RiskScore");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserEmail");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.MercekIncident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incidentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("AssignedUserCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assignedusercode");

                    b.Property<int?>("AssignmentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("assignmentgroupid");

                    b.Property<string>("CallTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calltypeid");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closedate");

                    b.Property<int?>("DefinitionCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("definitioncategoryid");

                    b.Property<string>("DefinitionCategoryPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("definitioncategorypath");

                    b.Property<string>("FlowStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flowstatusid");

                    b.Property<string>("ImpactId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("impactid");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("text")
                        .HasColumnName("incidentdescription");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opendate");

                    b.Property<string>("PriorityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priorityid");

                    b.Property<string>("RequestTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requesttypeid");

                    b.Property<string>("SolutionDescription")
                        .HasColumnType("text")
                        .HasColumnName("solutiondescription");

                    b.Property<string>("SolutionMethod")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("solutionmethod");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startdate");

                    b.Property<string>("StatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statusid");

                    b.Property<string>("SummaryDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summarydescription");

                    b.Property<DateTime?>("SystemDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("systemdate");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("IncidentId");

                    b.HasIndex("AssignedUserCode");

                    b.HasIndex("CloseDate");

                    b.HasIndex("OpenDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("SystemDate");

                    b.HasIndex("UserName");

                    b.ToTable("merceks", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.NdaDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Banka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("banka");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Denetim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("denetim");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<bool>("Egitim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("egitim");

                    b.Property<bool>("HasNda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_nda");

                    b.Property<bool>("Hukuk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hukuk");

                    b.Property<bool>("IsPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_personal");

                    b.Property<bool>("IsUnknown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unknown");

                    b.Property<bool>("IstirakDomain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("istirak_domain");

                    b.Property<bool>("Noter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("noter");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("HasNda");

                    b.HasIndex("IsPersonal");

                    b.HasIndex("IsUnknown");

                    b.ToTable("nda_domains", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.PolicyRuleException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exception_name");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("policy_name");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rule_name");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionName");

                    b.HasIndex("PolicyName");

                    b.HasIndex("PolicyName", "ExceptionName");

                    b.ToTable("policy_rule_exceptions", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.ReleasedIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AdminName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("admin_name");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<DateTime>("IncidentTimestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("incident_timestamp");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("task_name");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("AdminName");

                    b.HasIndex("IncidentId");

                    b.HasIndex("IncidentTimestamp");

                    b.HasIndex("UpdateTime");

                    b.HasIndex("IncidentId", "UpdateTime")
                        .IsUnique();

                    b.ToTable("released_incidents", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.UserDailyRiskScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgMaxMatches")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_max_matches");

                    b.Property<double>("AvgRiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("avg_risk_score");

                    b.Property<int>("BlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("block_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("DailyRiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("daily_risk_score");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("IncidentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("incident_count");

                    b.Property<int>("MaxMaxMatches")
                        .HasColumnType("integer")
                        .HasColumnName("max_max_matches");

                    b.Property<int>("MaxRiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_risk_score");

                    b.Property<int>("PermitCount")
                        .HasColumnType("integer")
                        .HasColumnName("permit_count");

                    b.Property<int>("QuarantineCount")
                        .HasColumnType("integer")
                        .HasColumnName("quarantine_count");

                    b.Property<int>("ReleasedCount")
                        .HasColumnType("integer")
                        .HasColumnName("released_count");

                    b.Property<string>("Team")
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail", "Date")
                        .IsUnique();

                    b.ToTable("user_daily_risk_scores", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.UserRiskTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<string>("TrendDirection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trend_direction");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.ToTable("user_risk_trends", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DomainFeatureValue", b =>
                {
                    b.HasOne("DLP.RiskAnalyzer.Shared.Models.NdaDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DLP.RiskAnalyzer.Shared.Models.DomainFeatureDefinition", "Feature")
                        .WithMany("Values")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DomainFeatureDefinition", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
