// <auto-generated />
using System;
using System.Collections.Generic;
using DLP.RiskAnalyzer.Analyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DLP.RiskAnalyzer.Analyzer.Migrations
{
    [DbContext(typeof(AnalyzerDbContext))]
    partial class AnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DLP.RiskAnalyzer.Analyzer.Data.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgRiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_risk_score");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DepartmentsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("departments_affected");

                    b.Property<int>("HighRiskCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_risk_count");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<int>("UniqueUsers")
                        .HasColumnType("integer")
                        .HasColumnName("unique_users");

                    b.HasKey("Id");

                    b.ToTable("daily_summaries", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.DepartmentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgRiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_risk_score");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<int>("HighRiskCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_risk_count");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<int>("UniqueUsers")
                        .HasColumnType("integer")
                        .HasColumnName("unique_users");

                    b.HasKey("Id");

                    b.ToTable("department_summaries", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<int>("DataSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("data_sensitivity");

                    b.Property<string>("DataType")
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<List<string>>("IOBs")
                        .HasColumnType("text[]");

                    b.Property<string>("Policy")
                        .HasColumnType("text")
                        .HasColumnName("policy");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<int>("RepeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("repeat_count");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("Id", "Timestamp");

                    b.HasIndex("Department");

                    b.HasIndex("RiskScore");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserEmail");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("DLP.RiskAnalyzer.Shared.Models.UserRiskTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<int>("TotalIncidents")
                        .HasColumnType("integer")
                        .HasColumnName("total_incidents");

                    b.Property<string>("TrendDirection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trend_direction");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.ToTable("user_risk_trends", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
